version: '3.3'

services:
  flask:
    image: rbekker87/flask-containername
    ports:
      - "80:5000"
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 1
networks:
  appnet:
    driver: overlay
